export const recipesArray = [
  {
    name: "Raspberry Cupcake",
    images: [
      "https://images.pexels.com/photos/1055272/pexels-photo-1055272.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "https://bonnibakery.com/wp-content/uploads/2022/04/Raspberry-Cupcakes2954-4-720x720.jpg",
    ],
    description:
      "These fresh raspberry cupcakes are a super cute spring bake, or great for something like valentine’s day because of their naturally pretty pink color",
    ingredients: [
      "½ cup Butter 113g",
      "1 cup White Sugar 200g",
      "1 Egg",
      "1 ½ cups All-purpose Flour 190g",
      "½ cup Raspberry Coulis 120g (as prepared above)",
      "⅓ cup Milk 80g",
      "1 teaspoon Baking Powder",
      "½ teaspoon Baking Soda",
      "½ teaspoon Salt",
      "1 teaspoon Vanilla Extract",
    ],
    directions: [
      "Preheat oven to 350°F / 180°C and line a cupcake pan with cupcake liners.",
      "Cream butter and sugar together until pale and fluffy.",
      "Add egg and stir until combined.",
      "Combine flour, baking powder, baking soda and salt in a bowl. Add half of the flour mixture to the batter and mix in completely.",
      "Add the milk, vanilla and ½ cup of the prepared and cooled raspberry puree. Keep the rest of the puree for the filling and frosting later.",
      "Mix in the milk and raspberry completely, then add the remaining flour and stir in. It should be a beautiful pink colour.",
      "Scoop cupcake batter into cupcake liners and bake for 17 minutes or until the tops of the cupcakes spring back when you press them lightly.",
      "Let the cupcakes sit for a few minutes after removing from the oven, then transfer to a wire rack to cool completely.",
      "Once cooled, use a cupcake corer or a spoon to scoop out a hole in the centre of each cupcake and fill with 1 teaspoon of raspberry coulis.",
    ],
  },
  {
    name: "Chocolate Brownie",
    images: [
      "https://images.pexels.com/photos/13219844/pexels-photo-13219844.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    description:
      "Indulge in the rich and fudgy goodness of chocolate brownies. These moist and decadent treats are perfect for satisfying your sweet cravings.",
    ingredients: [
      "1 cup Butter",
      "2 cups Granulated Sugar",
      "4 large Eggs",
      "1 teaspoon Vanilla Extract",
      "1 cup All-purpose Flour",
      "3/4 cup Unsweetened Cocoa Powder",
      "1/2 teaspoon Baking Powder",
      "1/4 teaspoon Salt",
      "1 cup Chocolate Chips",
    ],
    directions: [
      "Preheat oven to 350°F / 180°C. Grease and line a baking pan with parchment paper.",
      "In a large bowl, melt the butter and stir in the sugar until well combined.",
      "Add the eggs one at a time, beating well after each addition. Stir in the vanilla extract.",
      "In a separate bowl, whisk together the flour, cocoa powder, baking powder, and salt.",
      "Gradually add the dry ingredients to the wet ingredients, mixing until just combined. Fold in the chocolate chips.",
      "Pour the batter into the prepared baking pan and spread it evenly.",
      "Bake for 25-30 minutes or until a toothpick inserted in the center comes out with a few moist crumbs.",
      "Let the brownies cool in the pan for about 10 minutes, then transfer to a wire rack to cool completely.",
      "Cut into squares and enjoy!",
    ],
  },
  {
    name: "Lemon Blueberry Muffins",
    images: [
      "https://images.pexels.com/photos/8017963/pexels-photo-8017963.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    ],
    description:
      "Enjoy the burst of tangy lemon and juicy blueberries in these delightful muffins. Perfect for breakfast or as a light and refreshing snack.",
    ingredients: [
      "1 1/2 cups All-purpose Flour",
      "1/2 cup Granulated Sugar",
      "2 teaspoons Baking Powder",
      "1/4 teaspoon Baking Soda",
      "1/4 teaspoon Salt",
      "1/2 cup Buttermilk",
      "1/4 cup Vegetable Oil",
      "1 large Egg",
      "1 teaspoon Vanilla Extract",
      "Zest of 1 Lemon",
      "1 cup Fresh Blueberries",
    ],
    directions: [
      "Preheat oven to 375°F / 190°C. Line a muffin tin with paper liners.",
      "In a large bowl, whisk together the flour, sugar, baking powder, baking soda, and salt.",
      "In a separate bowl, mix together the buttermilk, vegetable oil, egg, vanilla extract, and lemon zest.",
      "Add the wet ingredients to the dry ingredients and stir until just combined.",
      "Gently fold in the fresh blueberries.",
      "Divide the batter evenly among the muffin cups.",
      "Bake for 18-20 minutes or until a toothpick inserted in the center of a muffin comes out clean.",
      "Allow the muffins to cool in the tin for a few minutes before transferring them to a wire rack to cool completely.",
      "Serve and enjoy these delicious lemon blueberry muffins!",
    ],
  },
];
